<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Globals">
    <WebView2EnableCsWinRTProjection>True</WebView2EnableCsWinRTProjection>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>NSDanmaku.WinUI</RootNamespace>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
    <Title>NSDanmaku.WinUI</Title>
    <Authors>xiaoyaocz</Authors>
    <Company>xiaoyaocz</Company>
    <Description>一个简单的WinUI3弹幕控件</Description>
    <PackageProjectUrl>https://github.com/xiaoyaocz/NSDanmaku</PackageProjectUrl>
    <RepositoryUrl>https://github.com/xiaoyaocz/NSDanmaku</RepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Controls\Danmaku.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Graphics.Win2D" Version="1.3.2" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.4654" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250606001" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="Controls\Danmaku.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  
</Project>